[package]
name = "tuic-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.1"
seahash = { version = "4.1", features = ["use_std"] }
thiserror = "1.0"
tokio = { version = "1.15", default-features = false }
