[package]
name = "tuic-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tuic-protocol = { path="../protocol" }

bytes = "1.1"
futures-util = { version = "0.3", default-features = false }
getopts = "0.2"
quinn = "0.8"
rustls = { version = "0.20", features = ["quic"], default-features = false }
seahash = { version = "4.1", features = ["use_std"] }
thiserror = "1.0"
tokio = { version = "1.15", features = ["io-util", "macros", "rt-multi-thread"] }
